//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVenta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosDeta
    {
        public int idpedido { get; set; }
        public int idproducto { get; set; }
        public decimal precioUnidad { get; set; }
        public int cantidad { get; set; }
        public string descuento { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
