//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVenta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosCabe
    {
        public int idpedidocabe { get; set; }
        public int idcliente { get; set; }
        public System.DateTime fechaPedida { get; set; }
        public System.DateTime fechaEntrega { get; set; }
        public System.DateTime fechaEnvio { get; set; }
        public string pedidoscabecol { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
