//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVenta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.PedidosDetas = new HashSet<PedidosDeta>();
        }
    
        public int idproducto { get; set; }
        public string nombreProducto { get; set; }
        public string descripcion { get; set; }
        public int idcategoria { get; set; }
        public decimal precioUnidad { get; set; }
        public int stock { get; set; }
        public int idproveedor { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosDeta> PedidosDetas { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
